### ISSUE TITLE
searchbar 的 onClear 事件不触发

### ISSUE THREAD

**Issue by bug4j** [psaren/taro-ui-vue#106]
**问题描述**
searchBar 绑定了 onChange事件和 onClear事件，点击 clear 图标 触发了onchange,但是没有触发onClear

**复现步骤**
- template
```html
<AtSearchBar :onChange="onSearchKeyChanged" @clear="onSearchClear" :value="searchKey" :onActionClick="onSearch"></AtSearchBar>
```
```js
methods:{
 onSearchKeyChanged(val) { 
  console.log(val);
 },
  onSearchClear() {
    console.log('cleared');
  }
}
```

**期望行为**
正常触发clear事件

**报错信息**
无

**系统信息**
 - Taro 版本：0.0.7
 - Taro UI Vue 版本：1.0.0-beta.8
 - 报错平台：weapp

**补充信息**
看了下源码，AtSearchBar.ts 的 props 和 data 里面根本没有 onClear ,
但是在实际触发clear时，代码里面判断了有没有绑定onClear
```js
handleClear(event: CommonEvent): void {
      if (this.onClear) {
        this.onClear(event);
      } else {
        this.onChange('', event)
      }
    },
```
*所以这个bug就很没水平了*

**Comment by psaren** [comment]
请使用
```ts
:onClear=“onSearchClear”
```
不要使用
```ts
@clear=“onSearchClear”
```

**Comment by bug4j** [comment]
> 请使用
> 
> ```ts
> :onClear=“onSearchClear”
> ```
> 
> 不要使用
> 
> ```ts
> @clear=“onSearchClear”
> ```

代码贴错了，使用
```html
<AtSearchBar  onClear="onSearchClear" />
```
也无法触发对应的方法

**Comment by bug4j** [comment]
> 请使用
> 
> ```ts
> :onClear=“onSearchClear”
> ```
> 
> 不要使用
> 
> ```ts
> @clear=“onSearchClear”
> ```

代码贴错了，使用
```html
<AtSearchBar  onClear="onSearchClear" />
```
也无法触发对应的方法
