### ISSUE TITLE
AtImagePicker 设置count无效

### ISSUE THREAD

**Issue by xxvv** [psaren/taro-ui-vue#109]
**问题描述**

AtImagePicker 设置count无效
**复现步骤**

```js
// 这里可以贴代码
```
import {  AtImagePicker } from 'taro-ui-vue'
<AtImagePicker
        multiple
        :count="5"
        length="4"
        :files="files"
        :on-change="onChange"
        :on-image-click="onImageClick"
      />
**期望行为**

count生效
**报错信息**

**系统信息**

Taro CLI 3.1.3 environment info:
    System:
      OS: macOS 11.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.12.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.1.3 => 3.1.3 
      @tarojs/components: 3.1.3 => 3.1.3 
      @tarojs/mini-runner: 3.1.3 => 3.1.3 
      @tarojs/runtime: 3.1.3 => 3.1.3 
      @tarojs/taro: 3.1.3 => 3.1.3 
      @tarojs/webpack-runner: 3.1.3 => 3.1.3 
      babel-preset-taro: 3.1.3 => 3.1.3 
      eslint-config-taro: 3.1.3 => 3.1.3 

weapp
**补充信息**

**Comment by psaren** [comment]
fix in taro-ui-vue@1.0.0-beta.9
