### ISSUE TITLE
tag 标签点击active状态改变不了

### ISSUE THREAD

**Issue by chen-cvresearch** [psaren/taro-ui-vue#118]
<AtTag name='db' :active="dbactive" type='primary' circle :onClick="onClick">家庭</AtTag>

onClick(e) {
      console.log(e)
      this.dbactive = true
    }

active属性可以被dbactive初始化，但点击标签后没变化。

**Comment by psaren** [comment]
请按issues模板填写下具体信息哈
然后可以提供下具体代码吗

**Comment by chen-cvresearch** [comment]
> 请按issues模板填写下具体信息哈
> 然后可以提供下具体代码吗

你们提供的小程序体验里，tag就不可点击。所以跟具体代码应该没关系。

**Comment by psaren** [comment]
@chen-cvresearch 
现在起码知道是在小程序体验的问题，因为文档里的 H5 demo 是正常的
PS: 以后提issue还是应该把问题描述清楚

**Comment by psaren** [comment]
原来的demo有问题，更新了，可以重新扫码，tag可以变为active
