### ISSUE TITLE
AtSwipeAction 不能触发 onClosed和onOpened事件

### ISSUE THREAD

**Issue by Xubinming** [psaren/taro-ui-vue#126]
<AtSwipeAction
      :options="[
        {
          text: '确认',
          style: {
            backgroundColor: '#FF4949'
          }
        }
      ]"
      :on-opened="handlellOpened"
      :on-closed="onClosed"
      :on-click="handleClicked"
    >
      <text>测试</text>
    </AtSwipeAction>
不能触发事件

**Comment by psaren** [comment]
请按照issue模板提供详细的信息，以便复现问题

**Comment by psrheartache** [comment]
问题同上，AtSwipeAction组件的onOpened和onClosed方法无法生效。
代码如下：
<AtList>
  <AtSwipeAction
    v-for="(item, index) in list"
    :key="item.title + index"
    :options="item.options"
    :is-opened="item.isOpened"
    :on-click="handleClicked"
    :on-opened="handleSingle"
  >
    <AtListItem :title="item.title" />
  </AtSwipeAction>
</AtList>
网址：http://taro-ui-vue.fontend.com/#/docs/swipeaction
官网的案例也无法正常展示。

**Comment by psrheartache** [comment]
非常感谢作者大大加班赶工， 已验证功能正常。  万分感谢。
