### ISSUE TITLE
swipe-action isOpened 参数无效

### ISSUE THREAD

**Issue by jpengj** [psaren/taro-ui-vue#129]
**问题描述**
isOpened 参数无法控制 SwipeAction 展开关闭状态

Taro UI 版本 1.0.0-beta.11

**复现步骤**
可见 Taro Ui Vue 小程序 SwipeAction 滑动操作示例

**报错信息**
无报错

**系统信息**
  Taro CLI 3.2.5 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - /usr/local/bin/node
      Yarn: 1.22.10 - ~/.npm-global/bin/yarn
      npm: 6.14.12 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.2.7 => 3.2.7 
      @tarojs/mini-runner: 3.2.7 => 3.2.7 
      @tarojs/runtime: 3.2.7 => 3.2.7 
      @tarojs/taro: 3.2.7 => 3.2.7 
      @tarojs/webpack-runner: 3.2.7 => 3.2.7 
      babel-preset-taro: 3.2.7 => 3.2.7 
      eslint-config-taro: 3.2.7 => 3.2.7

**Comment by psaren** [comment]
没看出什么问题，可以具体一点截个图说清楚吗

**Comment by jpengj** [comment]
![WechatIMG259](https://user-images.githubusercontent.com/32674989/126424232-d933ad37-e104-4da4-890d-aa84d4b639e1.jpeg)
![WechatIMG261](https://user-images.githubusercontent.com/32674989/126424239-281b986e-d8a4-4729-90a6-ee3d288b7b05.png)

这个是Taro-ui-vue 的示例小程序，看示例代码的意思，点击这个按钮将会触发右滑展开和关闭。但是这个开关没有起作用。
