### ISSUE TITLE
日历组件选取日期及滑动时，相应日期和月份未更新

### ISSUE THREAD

**Issue by b2nil** [psaren/taro-ui-vue#13]
**问题描述**
运行 Demo 后，发现`AtCalendar`组件存在几个问题：
- 点选日期后，没有突出显示，不能选取日期
- 滑动月份，控制栏的年月不会更新

另外微信小程序开发平台报错找不到 `View`、`Text` 的模板，应该是在 Vue template 中部分 tag 没有使用小写。 

**系统信息**
 - Taro 版本 ： v3.0.5
 - Taro UI Vue 版本: alpha.1
 - 报错平台 [h5, weapp] : weapp

**Comment by psaren** [comment]
#19 
修复并发布至 V1.0.0-alpha.3

**Comment by b2nil** [comment]
跑了一下 demo，发现：
- 滑动切换月份时，只能在上一个月、本月、下一个月之间滑动
- 选取日期时，在当前日期所在的月份选取，突出显示正常，但换到其他月份选择日期时，月份会跳到当前日期所在的月份
- Demo 页面没有显示「范围选择」的展示组件
