### ISSUE TITLE
AtTabBar的backgroundColor不生效

### ISSUE THREAD

**Issue by yimoodd** [psaren/taro-ui-vue#132]
**问题描述**
AtTabBar的backgroundColor不生效

**复现步骤**
```js
<AtTabBar
      background-color="#333"
      :tab-list="[...]"
    />
```

**期望行为**
Tabbar背景变黑

**报错信息**
Tabbar背景不变

**补充信息**
https://github.com/psaren/taro-ui-vue/blob/master/packages/taro-ui-vue/src/components/tab-bar/index.ts的props里面没有暴露backgroudColor，添加之后可解决

**Comment by psaren** [comment]
欢迎提PR

**Comment by psaren** [comment]
Fixed in 1.0.0-beta.16
