### ISSUE TITLE
两个ATinput 数据绑定相互影响

### ISSUE THREAD

**Issue by volitantlv** [psaren/taro-ui-vue#134]
<AtInput
          title="联系电话:"
          type="phone"
          required
          placeholder="请输入电话"
          :value="form.wssTel"
          :onChange="e => form.wssTel = e"
        />
        
        <atInput
          title="发布人:"
          required
          placeholder="请输入发布人"
          :onChange="e => form.wssCrePersonName =e"
          :value="form.wssCrePersonName"
        />
当我使用两个input的时候,第一个数据改变会影响到下面一个的数据

**Comment by volitantlv** [comment]
![image](https://user-images.githubusercontent.com/52948563/129804653-fc54c849-8bec-4005-810a-0a9501ad0e7c.png)

**Comment by volitantlv** [comment]
但是下面的不会影响上面的

**Comment by psaren** [comment]
AtInput
需要传name属性，作为输入框的唯一标识
