### ISSUE TITLE
h5 未正常显示taro ui vue

### ISSUE THREAD

**Issue by whosyourka** [psaren/taro-ui-vue#14]
windows，我用taro init创建版本，然后添加taro ui vue版本0.0.9，添加atbutton然后npm run dev:h5，结果h5 版本未成功显示taro ui vue，支付宝和微信小程序显示正常。我使用demo，h5是正常的。
taro info
Taro CLI 3.0.5 environment info:
System:
OS: Windows 10
Binaries:
Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.4 - C:\Users\whosy\AppData\Roaming\npm\yarn.CMD
npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by whosyourka** [comment]
windows，我用taro init创建版本，然后添加taro ui vue版本0.0.9，添加atbutton然后npm run dev:h5，结果h5 版本未成功显示taro ui vue，支付宝和微信小程序显示正常。我使用demo，h5是正常的。
taro info
Taro CLI 3.0.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\whosy\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by whosyourka** [comment]
在config/index已添加 h5 添加了 esnextModules: ['taro-ui-vue'],  还是未显示

**Comment by psaren** [comment]
taro-ui-vue 已经完成重构
建议升级至最新版本

**Comment by whosyourka** [comment]
已升级成功，h5显示正常
