### ISSUE TITLE
 taro-ui-vue-demo 全局组件 DocsHeader 样式失效

### ISSUE THREAD

**Issue by b2nil** [psaren/taro-ui-vue#15]
问题描述
Demo 的全局组件 `DocsHeader` 样式失效。
貌似是由于 `scoped` style 导致，删除 `scoped` 后样式恢复。
```vue
<style lang="scss" scoped>
.doc-header {
  display: flex;
  ...
```

系统信息

Taro 版本 ： v3.0.5
Taro UI Vue 版本: refactored alpha.2
报错平台 [h5, weapp] : weapp

**Comment by psaren** [comment]
@b2nil 欢迎 PR

**Comment by b2nil** [comment]
@psaren 好的。
有几个小问题我已经改了，先把问题提出来，我一起提 PR。
