### ISSUE TITLE
Picker组件 微信小程序 onChange/onCancel事件无法触发

### ISSUE THREAD

**Issue by fashioncj** [psaren/taro-ui-vue#22]
http://taro-ui-vue.fontend.com/#/docs/picker
官网示例直接运行，无法触发onChange、onCancel事件

"taro-ui-vue": "^1.0.0-alpha.4",

taro 3.0.5

**Comment by psaren** [comment]
原文档有误
需按下面的写法
```vue 
<picker
   mode='selector'
   :range="selector"
   :value="selectorValue"
   @change="handleChange"
   @cancel="handleCancel"
>
```

@change,
@cancel,
@columnchange（多列选择）

文档已更新 [picker](http://taro-ui-vue.fontend.com/#/docs/picker)
