### ISSUE TITLE
新建项目入口文件引用taro-ui-vue报错

### ISSUE THREAD

**Issue by BeckZhang7721** [psaren/taro-ui-vue#23]
错误信息：
`./node_modules/taro-ui-vue/src/components/button/index.ts
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: E:\project\taro\myApp\node_modules\taro-ui-vue\src\components\button\index.ts: Unexpected token, expected "," (144:21)`

`  142 |   methods: {
  143 |     classNames,
> 144 |     handleClick(event: CommonEvent) {
      |                      ^
  145 |       if (!this.disabled) {
  146 |         this.onClick && this.onClick(event)
  147 |       }`

已添加 esnextModules: ['taro-ui-vue']

请问如何解决

**Comment by BeckZhang7721** [comment]
ts 设置为 true就好了 ...
好吧 我的

**Comment by dggrok** [comment]
请问怎么将ts设置为true，因为我的项目没有用ts

**Comment by dggrok** [comment]
> ts 设置为 true就好了 ...
> 好吧 我的

请问怎么设置ts，我的项目没有用ts

**Comment by BeckZhang7721** [comment]
对 就在这里修改 初始化项目的时候也有提示

**Comment by 11boboCodeaa** [comment]
谢谢你 泰罗！
