### ISSUE TITLE
AtButton 提示 openType 无法校验

### ISSUE THREAD

**Issue by AFatMan** [psaren/taro-ui-vue#25]
**问题描述**
taro编译为微信小程序,
AtButton openType设置为getUserInfo时
微信开发者工具控制台提示Invalid prop: custom validator check failed for prop "openType".
官方文档显示可以使用
![image](https://user-images.githubusercontent.com/37704690/89392140-b486d900-d73b-11ea-8f3c-e3c051711f5a.png)

**复现步骤**
`<AtButton
          type="primary"
          openType="getUserInfo"
          loading
          circle
        >登录</AtButton>`

**错误截图**
![image](https://user-images.githubusercontent.com/37704690/89392410-147d7f80-d73c-11ea-9ab0-864ce35332bb.png)
`[Vue warn]: Invalid prop: custom validator check failed for prop "openType".

found in

---> <AtButton> at node_modules/taro-ui-vue/src/components/button/index.vue
       <Index> at src/pages/login/index.vue
         <Anonymous>
           <Anonymous>
             <Root>`
**补充**
查看了对应文件
![image](https://user-images.githubusercontent.com/37704690/89391569-f6fbe600-d73a-11ea-8639-6a8ffdbcb3d2.png)

**Comment by psaren** [comment]
Already fixed in #30
