### ISSUE TITLE
AtTextarea 输入文字后字数不更新

### ISSUE THREAD

**Issue by AFatMan** [psaren/taro-ui-vue#34]
**问题描述**
编译为微信小程序时,
AtTextarea 输入文字字数不更新

**复现步骤**
vue文件代码
**template**
`<AtTextarea
              name="NOTE"
              class="note-input"
              :value="info.NOTE"
              :onChange="handleNoteInput"
              :maxLength=200
              :cursorSpacing=30
            ></AtTextarea>`

**js**
`export default {
  data: function () {
    return {
      info: {
        NOTE: "",
      },
    };
  },
  methods: {
    handleNoteInput: function (value) {
      this.info.NOTE = value;
    }
  },
};`

**报错信息**
![image](https://user-images.githubusercontent.com/37704690/89636227-dec2cd00-d8da-11ea-8bde-444d7db166ad.png)

**系统信息**
`
    "@tarojs/taro": "3.0.6",
    "taro-ui-vue": "^1.0.0-alpha.5",`

**Comment by psaren** [comment]
![image](https://user-images.githubusercontent.com/18643034/89644232-0cfbd900-d8ea-11ea-9dee-ada89ec98248.png)
无法复现啊，希望可以提供一下能复现的repo

**Comment by AFatMan** [comment]
sorry,是我在生命周期created时进行了异步请求覆盖了info的内容,我移除之后一切正常
