### ISSUE TITLE
引入taro-ui-vue报编译错误

### ISSUE THREAD

**Issue by lixiang** [psaren/taro-ui-vue#39]
**问题描述**

引入taro-ui-vue@alpha5 报编译错误，已开启ts:true

版本：

👽 Taro v3.0.6

  Taro CLI 3.0.6 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.6 => 3.0.6
      @tarojs/mini-runner: 3.0.6 => 3.0.6
      @tarojs/runtime: 3.0.6 => 3.0.6
      @tarojs/taro: 3.0.6 => 3.0.6
      @tarojs/webpack-runner: 3.0.6 => 3.0.6
      babel-preset-taro: 3.0.6 => 3.0.6
      eslint-config-taro: 3.0.6 => 3.0.6

错误：
yarn run dev:weapp

./node_modules/taro-ui-vue/src/components/image-picker/index.vue?vue&type=template&id=30bcf8bb)
Module Error (from ./node_modules/vue-loader/dist/templateLoader.js):

VueCompilerError: v-if branches must use compiler generated keys.
at /Users/lixiang/eduminiapp1/node_modules/taro-ui-vue/src/components/image-picker/index.vue:17:11
15 |            v-if="item.url"
16 |            class="at-image-picker__flex-item"
17 |            :key="i * length + j"
   |                            ^^^^^
18 |          >
   |  ^^^^^^^^^
19 |            <view class="at-image-picker__item">
   |  ^^^^^

目前错误都是在picker组件里面抛出。

**Comment by psaren** [comment]
请提供复现步骤

**Comment by b2nil** [comment]
这个问题我在选择 vue3 框架新建项目时也遇到过。
- taro init newProject （选择 vue3 + ts, vue2.0 没试过）
- yarn add taro-ui-vue
- 在新项目 `page/index/index` 页面中随便引用的一个 taro-ui-vue 的组件，例如 `AtButton`
- yarn dev:weapp

然后就会直接报上面的编译错误。

**Comment by psaren** [comment]
@b2nil 目前还不支持vue3

**Comment by b2nil** [comment]
所以我估计 @lixiang 是用了 vue3

**Comment by lixiang** [comment]
> 所以我估计 @lixiang 是用了 vue3

对 我是用的vue3 



> @b2nil 目前还不支持vue3

请问有vue3 支持计划吗？ 那我可以用vue2 + composition api吧 ？

**Comment by lixiang** [comment]
已实验 vue2 + composition api + taro-ui-vue 兼容 结贴 谢谢楼上2位帮助
