### ISSUE TITLE
Noticebar通告栏 随机显示，且无法滚动动画不连贯

### ISSUE THREAD

**Issue by liwuxi** [psaren/taro-ui-vue#45]
**问题描述**

1. 进入页面有时显示文字，有时不显示。
2. 在一段文字没有跑完的情况下，就会从头开始滚动，每次都比上次跑动多出一点点

**代码**

```js
<template>
  <view class="index">
    <AtNoticebar class="notice safe-area" icon="volume-plus" marquee :speed="speed">{{noticeData}}</AtNoticebar>
  </view>
</template>

<script>
export default {
  name: 'Index',
  data() {
    return {
      noticeData: '',
      speed: 80
    }
  },
  mounted () {
    this.getNoticeList();
  },
  methods: {
    getNoticeList() {
      const notice = [];
      http.get(GET_NOTICE_LIST).then(res => {
        res.result.map(item => {
          notice.push(`${item.userName}在${item.gmtModified}购买了商品`)
        })
        this.noticeData = notice.join('! ');
        console.log(this.noticeData)
      })
    }
  }
}
</script>
```

**报错信息**
无

**系统信息**
Vue 2.x

Taro CLI 3.0.7 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.8.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.7 => 3.0.7 
      @tarojs/mini-runner: 3.0.7 => 3.0.7 
      @tarojs/runtime: 3.0.7 => 3.0.7 
      @tarojs/taro: 3.0.7 => 3.0.7 
      @tarojs/webpack-runner: 3.0.7 => 3.0.7 
      babel-preset-taro: 3.0.7 => 3.0.7 
      eslint-config-taro: 3.0.7 => 3.0.7 

**补充信息**
去掉 `marquee` 显示一切正常
动画不连贯的问题在数据写死的情况下会消失，但文字随机显示的错误无法解决

**Comment by psaren** [comment]
看了你的问题，需要提供一下最小的可复现的 `repo`,  数据可以mock一下
还有这种问题是在 WEAPP 还是 H5

**Comment by liwuxi** [comment]
[repo link](https://github.com/liwuxi/taro-ui-vue-noticebar)

问题出现在 WEAPP ，H5没有测试不清楚是否有该问题

微信小程序开发者工具：1.03.2006090  基础调试库：2.12.2

**Comment by psaren** [comment]
![image](https://user-images.githubusercontent.com/18643034/91626391-469f9b80-e9e1-11ea-9da9-4c3cc9fee45b.png)
对于动态内容你需要在内容出来后再去渲染 noticebar
```vue
<AtNoticebar v-if="noticeData" class="notice safe-area" icon="volume-plus" marquee :speed="speed">{{noticeData}}</AtNoticebar>
```

**Comment by liwuxi** [comment]
已解决，Thx❤️
