### ISSUE TITLE
AtImagePicker删除图片时触发了选择事件

### ISSUE THREAD

**Issue by 15380831711** [psaren/taro-ui-vue#47]
**问题描述**
AtImagePicker删除最后1张图片时，会同时触发选择图片事件：
![image](https://user-images.githubusercontent.com/33061032/91963423-6cf66b80-ed40-11ea-93f4-1f9a7ac9e53b.png)

**复现步骤**
```
<AtImagePicker mode="top" :files="files" :onChange="onChange" multiple :length="5" :showAddBtn="true" />

import { AtImagePicker } from 'taro-ui-vue';
    export default {
        components: {
            AtImagePicker,
        },
        data() {
            return {
                files: [],
            };
        },
        methods: {
            onChange(files) {
                this.files = files
            },
        }
    };
```

**系统信息**
    "dependencies": {
        "@babel/runtime": "^7.11.2",
        "@tarojs/components": "3.0.8",
        "@tarojs/runtime": "3.0.8",
        "@tarojs/taro": "3.0.8",
        "taro-ui-vue": "^1.0.0-alpha.6",
        "vue": "^2.6.12",
        "vue-template-compiler": "^2.6.12"
    },

**Comment by 15380831711** [comment]
onChange 事件中加个“延时”则不会触发选择事件。可能是删除后，图片被“+”占位，瞬间触发了“+”的tap事件。
```
            onChange(files, type) {
                setTimeout(() => {
                    this.files = files;
                });
            },
```

**Comment by psaren** [comment]
检查了下，这个问题是由于重复的 key 导致的
