### ISSUE TITLE
日历无法范围选择

### ISSUE THREAD

**Issue by wangjun521** [psaren/taro-ui-vue#56]
taro版本 3.0.10 引入 taro-ui-vue 时已使用 ts

单纯新建项目并且只引入了日历组件 日历范围选择器 第一个被选中日期有样式 点击第二个日期时无反应(范围效果也没有呈现) 再一次点击某一个日期时 这个日期被选中 选中效果如下
![image](https://i.loli.net/2020/09/17/prjBVKoclFDfM7h.png)

**Comment by b2nil** [comment]
贴代码看看吧

**Comment by wangjun521** [comment]
![](https://i.loli.net/2020/09/18/np94sYdJb6fIrmS.png)
就这点代码 其他什么都没有 如果我把 currentDate 去掉依旧不能范围选择
如果加上只有初始的时候是有范围选择的 如果点选了日期也会无法选中第二个

**Comment by b2nil** [comment]
@wangjun521 
没有绑定 `onSelectDate` 事件，这样试试：
```html
<AtCalendar
  isMultiSelect
  :currentDate="currentDate"
  :onSelectDate="handleSelectDates.bind(this)"
/>
```

```typescript
function handleSelectDates(selectedDates) {
    if(selectedDates.value.end) {
        this.curentDate = selectedDates.value
    }
}
```

**Comment by wangjun521** [comment]
喔  可行  这文档上真看不出来  哈哈哈 可能需要看源码才行啦 谢谢啦

**Comment by wangjun521** [comment]
![](https://i.loli.net/2020/09/18/IYQ5SfBNjkDxeRZ.png)
微信小程序没事但在支付宝小程序上显示不全  而且选中的日期范围显示是错误的 且上下滚动的时候月份不会变化
 尴尬

**Comment by wangjun521** [comment]
想偷个懒真的太难了 哈哈哈哈 只能等官方啦

**Comment by b2nil** [comment]
@wangjun521 
不要等官方啊，提 issue， 提 PR 啊。

临时可以手动将编译后的 base.axml 中 `<template name="tmpl_0_swiper"> 的 `onAnimationFinish` 改为 `onAnimationEnd`.

@psaren 
AtCalendar 设置为垂直滑动时，支付宝小程序中日期列表被遮住一行，是因为 `calendar.scss` 中缺少 `.at-calendar-slider__main--alipay`, 导致 `.main_body` 的高度没有设置。
```sass
.at-calendar-slider__main {
  .main__body {
   ...
  }

  &--weapp,
  &--alipay, // <- 增加
  &--swan {
    .main__body {
      height: 480px;
    }
  }
}
```
