### ISSUE TITLE
选择器没有实现吗？

### ISSUE THREAD

**Issue by zbq2019** [psaren/taro-ui-vue#63]
选择器还没有实现吗？

**Comment by psaren** [comment]
[picker](http://taro-ui-vue-demo.fontend.com/pages/form/picker/index)?

**Comment by zbq2019** [comment]
对，还想问一下swiper的数据通过接口请求就无法显示，静态数据就正常，这是怎么回事？似乎哪里都不能用setData这个方法，vue3.0

**Comment by psaren** [comment]
异步数据可以先用v-if在swiper上判断存在再去渲染

**Comment by zbq2019** [comment]
`getBannerList().then((r) => {
        if (r.data != null) {
          console.log("执行完成");
          console.log(r.data);
          that.imgUrls = r.data.data
          // 显示
          that.swiperShow = true;
        }
      });`
我这样操作了画面不渲染，我应该怎么弄

**Comment by psaren** [comment]
可以关注一下这个[Bug](https://github.com/NervJS/taro/issues/6179)

在swiper 上添加key
赋值时给 imgUrls 更新这个key
``` vue
<swiper
  ...
  :key="`${imgUrls.length}`">
</swiper>
```

**Comment by zbq2019** [comment]
好的，谢谢

**Comment by zbq2019** [comment]
方便加我微信指导一下吗？还是用不了，v 845229903

**Comment by psaren** [comment]
两秒后渲染 swiper
``` 
mounted() {
    setTimeout(() => {
      this.imgUrls = [
        'https://img10.360buyimg.com/babel/s700x360_jfs/t25855/203/725883724/96703/5a598a0f/5b7a22e1Nfd6ba344.jpg!q90!cc_350x180',
        'https://img11.360buyimg.com/babel/s700x360_jfs/t1/4776/39/2280/143162/5b9642a5E83bcda10/d93064343eb12276.jpg!q90!cc_350x180',
        'https://img14.360buyimg.com/babel/s700x360_jfs/t1/4099/12/2578/101668/5b971b4bE65ae279d/89dd1764797acfd9.jpg!q90!cc_350x180',
      ]
    }, 2000)
  },
```

![swiper](https://user-images.githubusercontent.com/18643034/94833305-8ffc6400-0441-11eb-840e-563bcc8555ba.gif)

taro-ui-vue-demo 源码改的 [swiper/index.vue](https://github.com/psaren/taro-ui-vue/blob/master/packages/taro-ui-vue-demo/src/pages/view/swiper/index.vue)
![image](https://user-images.githubusercontent.com/18643034/94832641-b8d02980-0440-11eb-9777-319a43c8ce04.png)

**Comment by zbq2019** [comment]
好的，谢谢
