### ISSUE TITLE
页面级传参数，获取不到值

### ISSUE THREAD

**Issue by smarttang** [psaren/taro-ui-vue#65]
**问题描述**
在页面传参数的时候，获取不到页面的内容。

**复现步骤**
```
  created() {
    console.log(getCurrentInstance().router.params.id)
  },

```

**期望行为**
获取到内容...

**报错信息**
返回就是空的{}

**系统信息**

**补充信息**

**Comment by smarttang** [comment]
![image](https://user-images.githubusercontent.com/4961402/94382727-5ccf8180-0170-11eb-8140-7dc9f98e466d.png)

现在就差这一个，其他页面都搞定了。哈哈～

**Comment by psaren** [comment]
这个与taro-ui-vue没有关系啊

const { id } = this.$taro.getCurrentInstance().router.params
console.log(id)

**Comment by smarttang** [comment]
啊，那这个咋办啊，我用这个也获取不到内容啊。。。

**Comment by smarttang** [comment]
输出的是undefined

**Comment by psaren** [comment]
可以参考 taro-ui-vue-demo 
https://github.com/psaren/taro-ui-vue/blob/fe09dce89eafe0e7f9f9155b863d47821f116621/packages/taro-ui-vue-demo/src/pages/panel/index.vue#L45-L46

**Comment by smarttang** [comment]
我太难了。。。我刚试了，一直都是获取不到值...一直undefined
```
  mounted() {
     const { id } = this.$taro.getCurrentInstance().router.params 
     const currentId = id 
     console.log(currentId)
    
  },
```

**Comment by psaren** [comment]
路由怎么写的

**Comment by smarttang** [comment]
路由就正常写啊。。
```
export default {
  pages: [
    'pages/index/index',
    'pages/course/index',
    'pages/learns/index',
    'pages/introduce/index'
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black'
  }
}
```

**Comment by smarttang** [comment]
来源点击跳转，跟案例一样。。h5下无效。。。
```
  methods: {
    handleClick(obj) {
      this.$taro.navigateTo({
        url: '/pages/introduce/index?id=${obj}'
      })
    }
  }
```
