### ISSUE TITLE
taro 3.0 vue版本，安装taro-ui-vue 报错

### ISSUE THREAD

**Issue by candyAndBella** [psaren/taro-ui-vue#68]
taro 3.0  安装的vue版本

选择了支持ts
然后运行成功
再安装taro-ui-vue
安装成功
运行就报错
![微信截图_20201009113623](https://user-images.githubusercontent.com/34698384/95540643-e100ef00-0a23-11eb-9593-39a306e29b13.png)

**Comment by smarttang** [comment]
按照Issue提问规则来吧，然后图裂了。

**Comment by psaren** [comment]
不会时选了vue3吧，暂时还未支持vue3
