### ISSUE TITLE
AtInput maxlength 失效

### ISSUE THREAD

**Issue by lice001** [psaren/taro-ui-vue#85]
**问题描述**
AtInput maxlength 失效

**复现步骤**
源代码 错误
![image](https://user-images.githubusercontent.com/24491707/101282068-be196e00-380d-11eb-9e17-eb2f020c6000.png)

**期望行为**

     <input
        ...
        :maxlength="inputProps.maxLength"

**报错信息**
无报错信息

**系统信息**

 - Taro 版本 [3.0.18]
 - Taro UI Vue 版本 [^1.0.0-alpha.13]
 - 报错平台 [ weapp]

**Comment by psaren** [comment]
PR welcome！
