### ISSUE TITLE
AtNavBar表现不正确

### ISSUE THREAD

**Issue by qweasdzxcpkh** [psaren/taro-ui-vue#89]
**问题描述**
使用AtNavBar组件时出现非预期行为

**复现步骤**
taro init
使用Taro+vue, typescript，模板使用Taro-vue-ui模板

```vue
<template>
  <view class="index">
      <AtNavBar
        color="#000"
        leftIconType="chevron-left"
        rightFirstIconType='bullet-list'
      >
        navigation
      </AtNavBar>
  </view>
</template>

<script>
// 按需引入, 更小的应用体积
import { AtNavBar } from 'taro-ui-vue'
import "taro-ui-vue/dist/style/components/nav-bar.scss"
import "taro-ui-vue/dist/style/components/icon.scss"
import './index.less' 
export default {
  components: {
    AtNavBar,
  },
  data () {
    return {
    }
  },
}
</script>
```
若将
```vue
<AtNavBar
        color="#000"
        leftIconType="chevron-left"
        rightFirstIconType='bullet-list'
      >
        navigation
      </AtNavBar>
```
改为
```vue
<AtNavBar
        color="#000"
        leftIconType="chevron-left"
        rightFirstIconType='bullet-list'
      >
        <view>navigation</view>
      </AtNavBar>
```
则出现报错

**期望行为**
在小程序能呈现跟官方例子一样的效果
实际效果：
![image](https://user-images.githubusercontent.com/26856368/101618305-c8757b00-3a4c-11eb-8751-e8331e95b007.png)
![image](https://user-images.githubusercontent.com/26856368/101618534-1a1e0580-3a4d-11eb-9518-bac41e561fb6.png)

**系统信息**
👽 Taro v3.0.17

  Taro CLI 3.0.17 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.14.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.17 => 3.0.17 
      @tarojs/components: 3.0.17 => 3.0.17 
      @tarojs/mini-runner: 3.0.17 => 3.0.17 
      @tarojs/runtime: 3.0.17 => 3.0.17 
      @tarojs/taro: 3.0.17 => 3.0.17 
      @tarojs/webpack-runner: 3.0.17 => 3.0.17 
      babel-preset-taro: 3.0.17 => 3.0.17 
      eslint-config-taro: 3.0.17 => 3.0.17 
    npmGlobalPackages:
      typescript: 3.7.3

   taro-ui-vue版本: 1.0.0-alpha.14

**补充信息**

AtNavBar的嵌套子组件处理bug？

**Comment by psaren** [comment]
推荐先使用title，会在2020/12/13发版修复
