### ISSUE TITLE
微信小程序中imagePicker组件sourceType属性无法只限定用拍照类型

### ISSUE THREAD

**Issue by wwt444** [psaren/taro-ui-vue#95]
**问题描述**
imagePicker组件sourceType属性无法只限定用拍照类型,选择图片时仍然是相册中的图片
**复现步骤**

1. 设置sourceType="['camera']"
2. 点击加载还是去了相册加载图片
3. 无法限定只用拍照中的图片
4. 用原生中的api可以

```js
// 这里可以贴代码
  <view class="index">
    <text>{{ msg }}</text>
        <AtImagePicker
      :files="files"
      :onChange="onChange"
      :sourceType="['camera']"
    />
  </view>
```

**期望行为**

希望我设置了camera类型只用拍照中的图片
**报错信息**

**系统信息**

**Comment by psaren** [comment]
最新版本已修复
