### ISSUE TITLE
AtImagePicker 在 iOS 下无法选择图片

### ISSUE THREAD

**Issue by lh1me** [psaren/taro-ui-vue#96]
**问题描述**
从 beta4 更新到 beta5 后 AtImagePicker 在 iOS 下无法选择图片，模拟器正常

**期望行为**
正常选择图片

**报错信息**
vconsole无报错

**系统信息**

System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
      npm: 6.14.9 - ~/.nvm/versions/node/v14.15.3/bin/npm
    npmPackages:
      @tarojs/cli: ^3.0.23 => 3.0.23 
      @tarojs/components: ^3.0.23 => 3.0.23 
      @tarojs/mini-runner: ^3.0.23 => 3.0.23 
      @tarojs/runtime: ^3.0.23 => 3.0.23 
      @tarojs/taro: ^3.0.23 => 3.0.23 
      @tarojs/webpack-runner: ^3.0.23 => 3.0.23 
      babel-preset-taro: ^3.0.23 => 3.0.23 
      eslint-config-taro: ^3.0.23 => 3.0.23

**Comment by psaren** [comment]
``` vue
  <AtImagePicker
        :sourceType="['album']"
        :files="files1"
        :onChange="onChange.bind(this, 'files1')"
    />
```
需要指定 sourceType = ['album']  

下个版本会为 sourceType 添加默认值['album']
